scrum_security:
    resource: "@ScrumSecurityBundle/Resources/config/routing.yml"
    prefix:   /



igor_task:
    resource: "@IgorTaskBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation



acme_website:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix: /

_task_bundle:
    resource: @IgorTaskBundle/Controller/
    prefix: /tasks
    type: annotation

registration:
    resource: @ScrumSecurityBundle/Controller/
    type: annotation